name: Run C++ tests

run-name: Testing triggered by ${{ github.event_name }} off branch ${{ github.ref }}."
on:
  # Runs on pull requests
  pull_request:

  # Runs on push to main as well
  push:
    branches:
      - main

jobs:
  test-sfo-cpp:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tests triggered by a ${{ github.event_name }} off branch ${{ github.ref }}."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build the codebase with linux config
        run: bazel build --config=linux //...

      - name: Run tests
        run: bazel test //...